services:
  redis:
    image: redislabs/rejson
    # restart: always
    container_name: redis_json_server
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    # environment:
    # REDIS_REQUIREPASS: redis-password
